/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
//select * from venta where VTA_FECHA_VENTA between '2021-08-01' and '2021-08-06';
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.SpinnerNumberModel;
import javax.swing.JTable;
import javax.swing.table.TableColumn;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JTable;
//import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.JTextField;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
//import java.io.IOException;
import java.io.OutputStream;
//import java.net.URL;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.ResultSet;


/**
 *
 * @author Usuario
 */
public class Compras extends javax.swing.JFrame {

    /**
     * Creates new form probando
     */
    DBConeccion con = new DBConeccion();
    Connection conect = con.conectar();

    DefaultTableModel tabla_articulos_OCD_1=new DefaultTableModel();
    DefaultTableModel tabla_articulos_OCD_2=new DefaultTableModel();
        
    DefaultTableModel tabla_solicitud_pedido=new DefaultTableModel();

    
    
    
    public Compras() {
        initComponents();
        ////////////////////////////////////////////////////////////////////////
        //SE CREAN LAS COLUMNAS DE LA TABLA "LISTA PACK "
        tabla_articulos_OCD_1.addColumn("Lista de Artículos");
        this.table_Articulos_OCD_1.setModel(tabla_articulos_OCD_1);
        ////////////////////////////////////////////////////////////////////////
        tabla_articulos_OCD_2.addColumn("Artículo");
        tabla_articulos_OCD_2.addColumn("Cantidad");
        this.table_Articulos_OCD_2.setModel(tabla_articulos_OCD_2);
        ////////////////////////////////////////////////////////////////////////
        SpinnerNumberModel nm = new SpinnerNumberModel();
        nm.setMinimum(0);
        spinner_Cantidad_OCD.setModel(nm);
        ////////////////////////////////////////////////////////////////////////
        tabla_solicitud_pedido.addColumn("Número Pedido");
        tabla_solicitud_pedido.addColumn("Fecha Pedido");
        tabla_solicitud_pedido.addColumn("Cantidad de Artículos");
        tabla_solicitud_pedido.addColumn("Selección");
        this.table_Pedidos_Realizados.setModel(tabla_solicitud_pedido);
        
        
        Mostrar_Lista_Pedidos_Realizados();
        Agregar_Articulos_A_Pack();
        Consultar_Proveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public DefaultTableModel Agregar_Articulos_A_Pack(){
        //table_Articulos_Pack_1.sets
        //lista_articulo_pack.addElement("SENTENCIA SQL");
        String sql = "SELECT ART_NOMBRE FROM articulo ORDER BY ART_NOMBRE";
        String [] registros = new String[1];
        tabla_articulos_OCD_1.setRowCount(0);
        PreparedStatement pst = null;
        ResultSet rs = null;
        try {
            pst = conect.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                registros[0] = rs.getString("ART_NOMBRE");
                tabla_articulos_OCD_1.addRow(registros);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No se pudo mostrar tabla de articulos");
        }
       
        return tabla_articulos_OCD_1;
    }
    
    public DefaultTableModel Mostrar_Lista_Pedidos_Realizados(){
        
        String [] registros = new String[3];
        tabla_solicitud_pedido.setRowCount(0);
        String sql = "select ORC_ID_ORDEN_COMPRA, ORC_FECHA_ORD_COM, OCD_CANTIDAD\n" +
                     "from orden_Compra inner join orden_compra_detalle\n" +
                     "on orden_compra.ORC_ID_ORDEN_COMPRA = orden_compra_detalle.OCD_ID_ORD_COM\n" +
                     "order by ORC_ID_ORDEN_COMPRA;";
        
        PreparedStatement pst = null;
        ResultSet rs = null;
        int x=0;
        int y=0;
        int cont=0;
        //String y = "";
        try {
            pst = conect.prepareStatement(sql);
            rs = pst.executeQuery();
     
            while(rs.next()){
                y = rs.getInt("ORC_ID_ORDEN_COMPRA");
                if(rs.getInt("ORC_ID_ORDEN_COMPRA") == y){
                    registros[0] = rs.getString("ORC_ID_ORDEN_COMPRA");
                    registros[1] = rs.getString("ORC_FECHA_ORD_COM");  
                    x = rs.getInt("OCD_CANTIDAD") + x;  
                    //y= (String) x;
                    registros[2] = Integer.toString(x);
                    cont++;
                    tabla_solicitud_pedido.addRow(registros);
                }
                else{
                    x=0;
                    y = rs.getInt("ORC_ID_ORDEN_COMPRA");
                    //w=y;
                    if(rs.getInt("ORC_ID_ORDEN_COMPRA") == y){
                        registros[0] = rs.getString("ORC_ID_ORDEN_COMPRA");
                        registros[1] = rs.getString("ORC_FECHA_ORD_COM");  
                        x = rs.getInt("OCD_CANTIDAD") + x;  
                        //y= (String) x;
                        registros[2] = Integer.toString(x);
                    }
                }
                
                //tabla_solicitud_pedido.addRow(registros);
                
            }
            
            
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "No se pudo mostrar tabla");
        }
        
        addCheckBox_Detalle_Pedido_Realizado(3, table_Pedidos_Realizados);
 

        return tabla_solicitud_pedido;
    
    }
    
    
    
    private void Imprimir_Detalle_Pedidos_Realizado(){
        
        int i =0;
        while( i<tabla_solicitud_pedido.getRowCount()){
            if(IsSelected(i, 3, table_Pedidos_Realizados)){
                pk_oc.setText((String) table_Pedidos_Realizados.getValueAt(i, 0));
            }
            i++;
        }
        String aux;
        aux = pk_oc.getText();
        System.out.println(" gokuuuuuu " + aux);
        
        String sql = "select OCD_ID_ORD_COM, OCD_ID_ARTICULO, OCD_CANTIDAD, ART_VALOR\n" +
                     "from articulo inner join orden_compra_detalle on articulo.ART_ID_ARTICULO = orden_compra_detalle.OCD_ID_ARTICULO\n" +
                     "inner join orden_compra on orden_compra.ORC_ID_ORDEN_COMPRA = orden_compra_detalle.OCD_ID_ORD_COM\n" +
                     " WHERE ORC_ID_ORDEN_COMPRA = '"+aux+"'  order by OCD_ID_ORDEN_COMPRA_DET;";
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        String aux2;  
        int cantidad = 0;
        int valor = 0;
        int Total = 0;
        int TOTALTOTAL=0;
        try {
            pst = conect.prepareStatement(sql);
            rs = pst.executeQuery();
           
            OutputStream file = new FileOutputStream(new File("C:\\Users\\paul1\\OneDrive\\Escritorio\\Dream Gift PDF\\Detalle_Pedido_Realizados.pdf"));
            Document document = new Document();
           
            PdfWriter.getInstance((com.itextpdf.text.Document) document, file);
            document.open();
            PdfPTable tabla = new PdfPTable (5);
            Paragraph p = new Paragraph ("Detalle Pedidos Realizados \n\n", FontFactory.getFont("Arial",16,Font.ITALIC,BaseColor.BLACK));
       
            p.setAlignment(Element.ALIGN_CENTER);
            document.add(p);
            
            document.add(new Paragraph(""));
            
            
            float [] mediaceldas = {3.0f, 3.0f, 3.0f, 3.0f, 3.0f}; 
         
            tabla.setWidths(mediaceldas);
         
            tabla.addCell(new Paragraph("Número OC", FontFactory.getFont("Calibri",10,BaseColor.BLUE)));
            tabla.addCell(new Paragraph("Cód. Artículo", FontFactory.getFont("Calibri",10,BaseColor.BLUE)));
            tabla.addCell(new Paragraph("Cantidad", FontFactory.getFont("Calibri",10,BaseColor.BLUE)));
            tabla.addCell(new Paragraph("Valor", FontFactory.getFont("Calibri",10,BaseColor.BLUE)));
            tabla.addCell(new Paragraph("Total", FontFactory.getFont("Calibri",10,BaseColor.BLUE)));
       

            while(rs.next()){

                tabla.addCell(new Paragraph(rs.getString("OCD_ID_ORD_COM"), FontFactory.getFont("Calibri",9)));                  
                tabla.addCell(new Paragraph(rs.getString("OCD_ID_ARTICULO"), FontFactory.getFont("Calibri",9)));

                //tabla.addCell(new Paragraph(rs.getString("OCD_CANTIDAD"), FontFactory.getFont("Calibri",9)));
                cantidad = rs.getInt("OCD_CANTIDAD");
                tabla.addCell(new Paragraph(rs.getString("OCD_CANTIDAD"), FontFactory.getFont("Calibri",9)));

                //tabla.addCell(new Paragraph(rs.getString("ART_VALOR"), FontFactory.getFont("Calibri",9)));
                valor = rs.getInt("ART_VALOR");
                tabla.addCell(new Paragraph(rs.getString("ART_VALOR"), FontFactory.getFont("Calibri",9)));

                Total = cantidad * valor;
                tabla.addCell(new Paragraph("$ "+ Total, FontFactory.getFont("Calibri",9)));
                TOTALTOTAL=TOTALTOTAL+Total;
                cantidad = 0;
                valor = 0;
                Total = 0;
          
            }           
           
            document.add(tabla); 

            Paragraph t = new Paragraph ("total $ = "+TOTALTOTAL+" \n\n", FontFactory.getFont("Arial",16,Font.ITALIC,BaseColor.BLACK));
       
            t.setAlignment(Element.ALIGN_RIGHT);
            document.add(t);
            
            document.add(new Paragraph(""));
             
            document.close();
            file.close(); 
             

        } 
        catch (Exception e) {
        }
        
        try{
          File file = new File("C:\\Users\\paul1\\OneDrive\\Escritorio\\Dream Gift PDF\\Detalle_Pedido_Realizados.pdf");
          Desktop.getDesktop().open(file);
       }   
      catch (Exception e){
        e.printStackTrace();
         }
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
 
    private void Agregar_Articulo_Pack(){
        int FilaSeleccioanda = table_Articulos_OCD_1.getSelectedRow();
        if(FilaSeleccioanda>=0){
            String datos[] = new String[2];
            datos[0] = table_Articulos_OCD_1.getValueAt(FilaSeleccioanda, 0).toString();
            datos[1] = spinner_Cantidad_OCD.getValue().toString(); 
            tabla_articulos_OCD_2.addRow(datos);
            tabla_articulos_OCD_1.removeRow(FilaSeleccioanda);
        }
    }
    private void Quitar_Articulo_Pack(){
        int FilaSeleccioanda = table_Articulos_OCD_2.getSelectedRow();
        if(FilaSeleccioanda>=0){
            String datos[] = new String[1];
            datos[0] = table_Articulos_OCD_2.getValueAt(FilaSeleccioanda, 0).toString();
            tabla_articulos_OCD_1.addRow(datos);
            tabla_articulos_OCD_2.removeRow(FilaSeleccioanda);
        }
    }
   
    
    public void Consultar_Proveedor(){
        String SQL = "SELECT PRO_NOMBRE FROM proveedor ORDER BY PRO_ID_RUT_PROVEEDOR ";
        String SQL2 = "SELECT PRO_ESTADO FROM proveedor ORDER BY PRO_ID_RUT_PROVEEDOR ";
        combobox_Proveedor_Solicitud_Pedido.removeAllItems();
        try {
            PreparedStatement pst = conect.prepareStatement(SQL);
            ResultSet rs = pst.executeQuery();
            PreparedStatement pst2 = conect.prepareStatement(SQL2);
            ResultSet rs2 = pst2.executeQuery();
            combobox_Proveedor_Solicitud_Pedido.addItem("Seleccione una opción"); 
            while(rs.next() && rs2.next()){
                if(rs2.getString("PRO_ESTADO").contentEquals("Activo")){
                    combobox_Proveedor_Solicitud_Pedido.addItem(rs.getString("PRO_NOMBRE"));
                }
            }
        } catch (Exception e) {}
    }
    
    
    
    public void addCheckBox_Detalle_Pedido_Realizado(int column, JTable table){
        TableColumn tc = table.getColumnModel().getColumn(column);
        tc.setCellEditor(table.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }

    ////////////////////////////////////////////////////////////////////////////
    public boolean IsSelected(int row, int column, JTable table){
        return table.getValueAt(row, column) != null;
    }
    
     
     
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jLabel17 = new javax.swing.JLabel();
        TabbedPane_COMPRAS = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        date_Fecha_Pedido_OC = new com.toedter.calendar.JDateChooser();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_Articulos_OCD_1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        table_Articulos_OCD_2 = new javax.swing.JTable();
        spinner_Cantidad_OCD = new javax.swing.JSpinner();
        btn_Agregar_Articulos_OCD = new javax.swing.JButton();
        btn_Quitar_Artículos_OCD = new javax.swing.JButton();
        btn_Guardar_Solicitud_Pedido = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        combobox_Proveedor_Solicitud_Pedido = new javax.swing.JComboBox<>();
        pk_oc = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_Guardar_Venta = new javax.swing.JButton();
        btn_Cancelar_Venta = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Pedidos_Realizados = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Numero_Pedido_Confirmacion = new javax.swing.JTextField();
        txt_Rut_Cliente_Confirmacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btn_Confirmación = new javax.swing.JButton();
        date_Fecha_Pago_Confirmacion = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        btn_Seleccionar_Confirmación = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_Detalle_Factura = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Factura_Compra_Inventariada = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_Numero_Pedido_Confirmacion1 = new javax.swing.JTextField();
        txt_Rut_Cliente_Confirmacion1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        btn_Confirmación1 = new javax.swing.JButton();
        date_Fecha_Pago_Confirmacion1 = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_Detalle_Factura_2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MENU_VENTAS = new javax.swing.JMenu();
        MENU_COMPRAS = new javax.swing.JMenu();
        MENU_INFORMES = new javax.swing.JMenu();
        MENU_MAESTROS = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu4.setText("jMenu4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenu7.setText("jMenu7");

        jLabel17.setText("jLabel17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 153, 255));

        TabbedPane_COMPRAS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabbedPane_COMPRASMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel38.setText("Fecha Pedido:");

        date_Fecha_Pedido_OC.setDateFormatString("yyyy-MM-dd");

        table_Articulos_OCD_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lista de Artículos"
            }
        ));
        jScrollPane5.setViewportView(table_Articulos_OCD_1);

        table_Articulos_OCD_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artículo", "Cantidad"
            }
        ));
        jScrollPane6.setViewportView(table_Articulos_OCD_2);

        btn_Agregar_Articulos_OCD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Agregar_Articulos_OCD.setText(">");
        btn_Agregar_Articulos_OCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Agregar_Articulos_OCDActionPerformed(evt);
            }
        });

        btn_Quitar_Artículos_OCD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_Quitar_Artículos_OCD.setText("<");
        btn_Quitar_Artículos_OCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Quitar_Artículos_OCDActionPerformed(evt);
            }
        });

        btn_Guardar_Solicitud_Pedido.setText("Guardar");
        btn_Guardar_Solicitud_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Guardar_Solicitud_PedidoActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");

        jLabel4.setText("Proveedor:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addGap(0, 485, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_Guardar_Solicitud_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(83, 83, 83)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_Quitar_Artículos_OCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Agregar_Articulos_OCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(spinner_Cantidad_OCD, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(combobox_Proveedor_Solicitud_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addGap(18, 18, 18)
                                    .addComponent(date_Fecha_Pedido_OC, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(pk_oc, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel38)
                        .addComponent(jLabel4)
                        .addComponent(combobox_Proveedor_Solicitud_Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_Fecha_Pedido_OC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(btn_Agregar_Articulos_OCD)
                            .addGap(12, 12, 12)
                            .addComponent(spinner_Cantidad_OCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Quitar_Artículos_OCD))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(pk_oc, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar_Solicitud_Pedido)
                    .addComponent(jButton4))
                .addGap(15, 15, 15))
        );

        jLabel18.setText("Solicitudes de pedido");

        btn_Guardar_Venta.setText("Generar OC");
        btn_Guardar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Guardar_VentaActionPerformed(evt);
            }
        });

        btn_Cancelar_Venta.setText("Editar");
        btn_Cancelar_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cancelar_VentaActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        table_Pedidos_Realizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número Pedido", "Fecha Pedido", "Cantidad de Artículos", "Selección"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table_Pedidos_Realizados);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Detalle Pedidos Realizados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Cancelar_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Guardar_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar_Venta)
                    .addComponent(btn_Guardar_Venta))
                .addContainerGap())
        );

        TabbedPane_COMPRAS.addTab("Solicitudes pedido", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Número Factura:");

        jLabel6.setText("Proveedor:");

        txt_Numero_Pedido_Confirmacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Numero_Pedido_ConfirmacionKeyReleased(evt);
            }
        });

        jLabel9.setText("Fehca Recepción:");

        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btn_Confirmación.setText("Guardar");
        btn_Confirmación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmaciónActionPerformed(evt);
            }
        });

        date_Fecha_Pago_Confirmacion.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Numero_Pedido_Confirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(txt_Rut_Cliente_Confirmacion))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_Fecha_Pago_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Confirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Numero_Pedido_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Rut_Cliente_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(date_Fecha_Pago_Confirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Confirmación)
                            .addComponent(jButton5))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Registro del Detalle de Factura ");

        btn_Seleccionar_Confirmación.setText("Eliminar");
        btn_Seleccionar_Confirmación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Seleccionar_ConfirmaciónActionPerformed(evt);
            }
        });

        jLabel31.setText("Registro Factura Proveedores");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        table_Detalle_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Número Pedido", "Fecha Pedido", "Nombre Cliente", "Rut Cliente", "Número Teléfono"
            }
        ));
        jScrollPane3.setViewportView(table_Detalle_Factura);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Código:");

        jLabel8.setText("Artículo:");

        jLabel10.setText("Cantidad:");

        jLabel13.setText("Valor:");

        jButton8.setText("Agregar Artículo");

        jButton9.setText("Cancelar");

        jLabel15.setText("Fecha Vencimiento:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 153, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8)
                        .addComponent(jButton9))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setText("Registro detalle de factura de proveedores");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Detalle de Factura");

        jButton10.setText("Editar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(251, 251, 251)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Seleccionar_Confirmación, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Seleccionar_Confirmación)
                    .addComponent(jButton10))
                .addContainerGap(1082, Short.MAX_VALUE))
        );

        TabbedPane_COMPRAS.addTab("Registro Compra", jPanel1);

        jButton1.setText("Descargar");

        jButton2.setText("Imprimir");

        jLabel32.setText("Revisión de facturas inventariadas");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        table_Factura_Compra_Inventariada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registro Venta", "Pack", "Destinatario", "Fecha Entrega", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(table_Factura_Compra_Inventariada);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setText("Número Factura:");

        jLabel19.setText("Rut:");

        txt_Numero_Pedido_Confirmacion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Numero_Pedido_Confirmacion1KeyReleased(evt);
            }
        });

        jLabel20.setText("Fehca Recepción:");

        jButton11.setText("Cancelar");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btn_Confirmación1.setText("Guardar");
        btn_Confirmación1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Confirmación1ActionPerformed(evt);
            }
        });

        date_Fecha_Pago_Confirmacion1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_Numero_Pedido_Confirmacion1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(txt_Rut_Cliente_Confirmacion1))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_Fecha_Pago_Confirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Confirmación1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_Numero_Pedido_Confirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_Rut_Cliente_Confirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(date_Fecha_Pago_Confirmacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Confirmación1)
                            .addComponent(jButton11))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Factura de Compra Inventariadas");

        jButton12.setText("Editar");

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        table_Detalle_Factura_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane4.setViewportView(table_Detalle_Factura_2);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalle Factura");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(317, 317, 317))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(322, 322, 322)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(723, Short.MAX_VALUE))
        );

        TabbedPane_COMPRAS.addTab("Revisión de facturas", jPanel4);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setText("Dream Gift");

        MENU_VENTAS.setText("Ventas");
        jMenuBar1.add(MENU_VENTAS);

        MENU_COMPRAS.setText("Compras");
        jMenuBar1.add(MENU_COMPRAS);

        MENU_INFORMES.setText("Informes");
        jMenuBar1.add(MENU_INFORMES);

        MENU_MAESTROS.setText("Maestros");
        MENU_MAESTROS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MENU_MAESTROSMouseClicked(evt);
            }
        });
        jMenuBar1.add(MENU_MAESTROS);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPane_COMPRAS)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TabbedPane_COMPRAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Cancelar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cancelar_VentaActionPerformed

        
    }//GEN-LAST:event_btn_Cancelar_VentaActionPerformed

    private void MENU_MAESTROSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MENU_MAESTROSMouseClicked
        // TODO add your handling code here:
        Maestros maestros = new Maestros();
        maestros.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MENU_MAESTROSMouseClicked

    private void TabbedPane_COMPRASMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabbedPane_COMPRASMouseClicked
        //Agregar_Articulos_A_Pack();
    }//GEN-LAST:event_TabbedPane_COMPRASMouseClicked

    private void btn_Guardar_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Guardar_VentaActionPerformed
        Imprimir_Detalle_Pedidos_Realizado();
               
    }//GEN-LAST:event_btn_Guardar_VentaActionPerformed

    private void txt_Numero_Pedido_ConfirmacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Numero_Pedido_ConfirmacionKeyReleased

    }//GEN-LAST:event_txt_Numero_Pedido_ConfirmacionKeyReleased

    private void btn_ConfirmaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmaciónActionPerformed
       
    }//GEN-LAST:event_btn_ConfirmaciónActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_Seleccionar_ConfirmaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Seleccionar_ConfirmaciónActionPerformed
       
    }//GEN-LAST:event_btn_Seleccionar_ConfirmaciónActionPerformed

    private void txt_Numero_Pedido_Confirmacion1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Numero_Pedido_Confirmacion1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Numero_Pedido_Confirmacion1KeyReleased

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btn_Confirmación1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Confirmación1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Confirmación1ActionPerformed

    private void btn_Agregar_Articulos_OCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Agregar_Articulos_OCDActionPerformed
        Agregar_Articulo_Pack();
    }//GEN-LAST:event_btn_Agregar_Articulos_OCDActionPerformed

    private void btn_Quitar_Artículos_OCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Quitar_Artículos_OCDActionPerformed
        Quitar_Articulo_Pack();
    }//GEN-LAST:event_btn_Quitar_Artículos_OCDActionPerformed

    private void btn_Guardar_Solicitud_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Guardar_Solicitud_PedidoActionPerformed
        
        String SQL_proveedor = "SELECT PRO_NOMBRE FROM proveedor ORDER BY PRO_ID_RUT_PROVEEDOR";
        String SQL2_proveedor = "SELECT PRO_ID_RUT_PROVEEDOR FROM proveedor ORDER BY PRO_ID_RUT_PROVEEDOR";
        String aux;
        try {
            PreparedStatement pst_nom_pro = conect.prepareStatement(SQL_proveedor);
            ResultSet rs_nom_pro = pst_nom_pro.executeQuery();
            PreparedStatement pst_id_pro = conect.prepareStatement(SQL2_proveedor);
            ResultSet rs_id_pro = pst_id_pro.executeQuery();
            
            PreparedStatement guardar = conect.prepareStatement("INSERT INTO orden_compra (ORC_FECHA_ORD_COM, ORC_ID_PROVEEDOR_ORD_COM) VALUES (?,?)");
            guardar.setString(1, ((JTextField) date_Fecha_Pedido_OC.getDateEditor().getUiComponent()).getText());           
            while(rs_nom_pro.next() && rs_id_pro.next()){
                aux = (String) combobox_Proveedor_Solicitud_Pedido.getSelectedItem();
                if(rs_nom_pro.getString("PRO_NOMBRE").contentEquals(aux)){
                    guardar.setString(2, rs_id_pro.getString("PRO_ID_RUT_PROVEEDOR"));
                }   
            }
        
            guardar.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro guardado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Registro no se guardó");
        }
        
        
        String sql = "select ORC_ID_ORDEN_COMPRA from orden_compra";
        pk_oc.setText("");
        
            try {
                PreparedStatement pst_pkoc = conect.prepareStatement(sql);
                ResultSet rs_pkoc = pst_pkoc.executeQuery();
                
                pk_oc.setText(rs_pkoc.getString("ORC_ID_ORDEN_COMPRA"));
                
            } catch (Exception e) {
            }
            
        String SQL = "SELECT ART_ID_ARTICULO FROM articulo ORDER BY ART_ID_ARTICULO";
        String SQL2 = "SELECT ART_NOMBRE FROM articulo ORDER BY ART_ID_ARTICULO";
        String SQL3 = "SELECT ORC_ID_ORDEN_COMPRA FROM orden_compra ORDER BY ORC_ID_ORDEN_COMPRA";
        int i=0;
        int x=0;
        while(i<tabla_articulos_OCD_2.getRowCount()){
            try {   
                PreparedStatement guardar2 = conect.prepareStatement("INSERT INTO orden_compra_detalle (OCD_CANTIDAD, OCD_ID_ARTICULO, OCD_ID_ORD_COM) VALUES (?,?,?)");
                PreparedStatement pst = conect.prepareStatement(SQL);
                ResultSet rs = pst.executeQuery();
                PreparedStatement pst2 = conect.prepareStatement(SQL2);
                ResultSet rs2 = pst2.executeQuery();
                
                
         
                PreparedStatement pst_id_OC = conect.prepareStatement(SQL3);
                ResultSet rs_id_OC = pst_id_OC.executeQuery();
                

                //x = (int) tabla_articulos_OCD_2.getValueAt(i, 1) + x;

                
                guardar2.setString(1, tabla_articulos_OCD_2.getValueAt(i, 1).toString());

                while(rs.next() && rs2.next()){
                    if((tabla_articulos_OCD_2.getValueAt(i, 0).toString()).contentEquals(rs2.getString("ART_NOMBRE"))){
                        guardar2.setString(2, rs.getString("ART_ID_ARTICULO"));

                    }
                }
                
                while(rs_id_OC.next()){

                    guardar2.setString(3, rs_id_OC.getString("ORC_ID_ORDEN_COMPRA"));
                    
                }
                
                guardar2.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registro guardado con exito");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e + "Registro no se guardó");
            }
            i++;
        }
            
            
            
            
            
            
        
        
        
        
        
    }//GEN-LAST:event_btn_Guardar_Solicitud_PedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MENU_COMPRAS;
    private javax.swing.JMenu MENU_INFORMES;
    private javax.swing.JMenu MENU_MAESTROS;
    private javax.swing.JMenu MENU_VENTAS;
    private javax.swing.JTabbedPane TabbedPane_COMPRAS;
    private javax.swing.JButton btn_Agregar_Articulos_OCD;
    private javax.swing.JButton btn_Cancelar_Venta;
    private javax.swing.JButton btn_Confirmación;
    private javax.swing.JButton btn_Confirmación1;
    private javax.swing.JButton btn_Guardar_Solicitud_Pedido;
    private javax.swing.JButton btn_Guardar_Venta;
    private javax.swing.JButton btn_Quitar_Artículos_OCD;
    private javax.swing.JButton btn_Seleccionar_Confirmación;
    private javax.swing.JComboBox<String> combobox_Proveedor_Solicitud_Pedido;
    private com.toedter.calendar.JDateChooser date_Fecha_Pago_Confirmacion;
    private com.toedter.calendar.JDateChooser date_Fecha_Pago_Confirmacion1;
    private com.toedter.calendar.JDateChooser date_Fecha_Pedido_OC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private javax.swing.JTextField pk_oc;
    private javax.swing.JSpinner spinner_Cantidad_OCD;
    private javax.swing.JTable table_Articulos_OCD_1;
    private javax.swing.JTable table_Articulos_OCD_2;
    private javax.swing.JTable table_Detalle_Factura;
    private javax.swing.JTable table_Detalle_Factura_2;
    private javax.swing.JTable table_Factura_Compra_Inventariada;
    private javax.swing.JTable table_Pedidos_Realizados;
    private javax.swing.JTextField txt_Numero_Pedido_Confirmacion;
    private javax.swing.JTextField txt_Numero_Pedido_Confirmacion1;
    private javax.swing.JTextField txt_Rut_Cliente_Confirmacion;
    private javax.swing.JTextField txt_Rut_Cliente_Confirmacion1;
    // End of variables declaration//GEN-END:variables
}
